const axios = require('axios');
const eNabizRepository = require('../repositories/ENabizRepository');
const patientRepository = require('../repositories/PatientRepository');

class ENabizService {
    constructor() {
        this.baseUrl = process.env.ENABIZ_API_URL || 'https://sys.saglik.gov.tr/rest/api';
        this.firmCode = process.env.ENABIZ_FIRM_CODE || 'DUMMY_CODE';
        this.firmPassword = process.env.ENABIZ_FIRM_PASSWORD || 'DUMMY_PWD';
    }

    /**
     * Helper to get STS/SYS Authorization token
     */
    async getToken() {
        if (!process.env.ENABIZ_API_URL) {
            console.log("ℹ️ [E-Nabız] Using mock token (No API URL provided)");
            return "MOCK_STS_TOKEN_12345";
        }
        
        try {
            // Real STS token request logic
            // const response = await axios.post(`${this.baseUrl}/token`, { clientId: this.firmCode, clientSecret: this.firmPassword });
            // return response.data.token;
            return "REAL_STS_TOKEN_PLACEHOLDER";
        } catch (error) {
            console.error("❌ [E-Nabız] Token fetch failed:", error.message);
            throw new Error('E-Nabiz token error');
        }
    }

    /**
     * Formats data into MSVS (Minimum Sağlık Veri Seti) standard
     */
    formatToMSVS(patientData, medicalData, actionType) {
        return {
            SYSTakipNo: "", // Generated by SYS later
            HastaBilgileri: {
                TCKimlikNo: patientData.tcNo || "11111111111",
                Ad: patientData.name.split(' ')[0],
                Soyad: patientData.name.split(' ').slice(1).join(' ') || "Bilinmiyor"
            },
            MuayeneBilgisi: {
                KlinikKodu: "2900", // Dental clinic code
                IslemTuru: actionType,
                Tarih: new Date().toISOString()
            },
            IslemBilgileri: medicalData
        };
    }

    async sendData(patientId, actionType, data, userId) {
        console.log(`🏥 [E-Nabız] Fetching patient & Processing ${actionType}`);
        
        const patient = await patientRepository.findById(patientId);
        if (!patient) throw new Error("Patient not found for E-Nabız submission");

        const msvsPayload = this.formatToMSVS(patient, data, actionType);
        // Do not log PII (TCNo, Name)
        console.log('📦 MSVS Payload Configured (PII Masked in Logs)');
        const transactionId = `TRX-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
        const logData = {
            patientId: patient._id,
            transactionId,
            actionType,
            status: 'PENDING',
            requestData: msvsPayload,
            submittedBy: userId
        };
        const log = await eNabizRepository.create(logData);

        try {
            const token = await this.getToken();
            let isSuccess = false;
            let responseData = {};

            if (!process.env.ENABIZ_API_URL) {
                // MOCK DELAY & LOGIC
                await new Promise(resolve => setTimeout(resolve, 1000));
                isSuccess = Math.random() > 0.05; // 95% success
                responseData = isSuccess ? {
                    sysTakipNo: `SYS-${Date.now()}`,
                    resultCode: '0000',
                    resultMessage: 'ISLEM BASARI ILE KAYDEDILDI'
                } : {
                    resultCode: '102',
                    resultMessage: 'MUKERRER KAYIT VEYA GECERSIZ HASTA BILGISI'
                };
            } else {
                // REAL API CALL
                const response = await axios.post(`${this.baseUrl}/sendMSVS`, msvsPayload, {
                    headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' }
                });
                responseData = response.data;
                isSuccess = responseData.resultCode === '0000';
            }

            // Update log
            const updateData = {
                status: isSuccess ? 'SUCCESS' : 'ERROR',
                responseData
            };

            if (!isSuccess) {
                updateData.errorCode = responseData.resultCode;
                updateData.errorMessage = responseData.resultMessage;
                console.error(`❌ [E-Nabız] Failed: ${updateData.errorMessage}`);
            } else {
                console.log(`✅ [E-Nabız] Success: ${responseData.sysTakipNo || 'N/A'}`);
            }

            await eNabizRepository.update({ _id: log._id }, updateData);
            
            return {
                success: isSuccess,
                transactionId,
                response: responseData
            };
            
        } catch (error) {
            console.error(`❌ [E-Nabız] Network/Fatal Error:`, error.message);
            await eNabizRepository.update({ _id: log._id }, {
                status: 'ERROR',
                errorCode: '500',
                errorMessage: error.message
            });
            throw error;
        }
    }
}

module.exports = new ENabizService();

